### ISSUE TITLE
issue in gotree 

### ISSUE THREAD

**Issue by cokelaer** [fredericlemoine/gotree#2]
Got this issue on travis today 2d Aug 2018.

github.com/fredericlemoine/gotree/tree/tree.go:1637:17: undefined: math.Round

**Comment by fredericlemoine** [comment]
You should build gotree using Go>=1.10.3 now (see 0ee8994ad5091bd7d7b866e597dd412d5471cdf5)

**Comment by fredericlemoine** [comment]
I guess it is about CI for biokit/bioconvert. I updated requirements_tools.txt here biokit/bioconvert@2598a73b5d756f64fbb860d8da7790178491c0a4 I hope it solves this issue.

**Comment by cokelaer** [comment]
great thanks
